import {
	siOpenjdk,
	siTypescript,
	siJavascript,
	siKotlin,
	siPython,
	siGo,
	siRust,
	siCplusplus,
	siPostgresql,
	siGnubash,
	siSpringboot,
	siReact,
	siVuedotjs,
	siAngular,
	siSvelte,
	siNextdotjs,
	siNestjs,
	siKtor,
	siDjango,
	siFlask,
	siFastapi,
	siJunit5,
	siPytest,
	siJest,
	siCypress,
	siGatling,
	siDocker,
	siKubernetes,
	siHelm,
	siIstio,
	siTerraform,
	siAnsible,
	siLinux,
	siGitlab,
	siGithubactions,
	siMongodb,
	siClickhouse,
	siNeo4j,
	siApachekafka,
	siRabbitmq,
	siCelery,
	siRedis,
	siMinio,
	siNginx,
	siTraefikproxy,
	siElasticsearch,
	siKeycloak,
	siVault,
	siElasticstack,
	siPrometheus,
	siGrafana,
	siPytorch,
	siScikitlearn,
	siApple,
	siHuggingface,
	siLangchain,
	siAnthropic,
	siOllama,
	siLmstudio,
	siGit,
	siZsh,
	siApachemaven,
	siGradle,
	siCmake,
	siNpm,
	siBun,
	siPostman,
	siBruno,
	siWireshark,
	siObsidian,
	siFigma,
	siJupyter,
	siN8n,
	siJira,
	siNeovim,
	siIntellijidea,
	siPycharm,
	type SimpleIcon
} from 'simple-icons';

type TechMeta = { icon: SimpleIcon | null; color: string };

export const techMeta: Record<string, TechMeta> = {
	Java: { icon: siOpenjdk, color: '#ED8B00' },
	TypeScript: { icon: siTypescript, color: '#3178C6' },
	JavaScript: { icon: siJavascript, color: '#F7DF1E' },
	Kotlin: { icon: siKotlin, color: '#7F52FF' },
	Python: { icon: siPython, color: '#3776AB' },
	Go: { icon: siGo, color: '#00ADD8' },
	Rust: { icon: siRust, color: '#000000' },
	'C++': { icon: siCplusplus, color: '#00599C' },
	SQL: { icon: siPostgresql, color: '#4479A1' },
	Bash: { icon: siGnubash, color: '#4EAA25' },

	'Spring Boot': { icon: siSpringboot, color: '#6DB33F' },
	React: { icon: siReact, color: '#61DAFB' },
	Vue: { icon: siVuedotjs, color: '#4FC08D' },
	Angular: { icon: siAngular, color: '#DD0031' },
	Svelte: { icon: siSvelte, color: '#FF3E00' },
	'Next.js': { icon: siNextdotjs, color: '#000000' },
	NestJS: { icon: siNestjs, color: '#E0234E' },
	Ktor: { icon: siKtor, color: '#087CFA' },
	Django: { icon: siDjango, color: '#092E20' },
	Flask: { icon: siFlask, color: '#000000' },
	FastAPI: { icon: siFastapi, color: '#009688' },

	JUnit: { icon: siJunit5, color: '#25A162' },
	Testcontainers: { icon: null, color: '#291A3F' },
	Pytest: { icon: siPytest, color: '#0A9EDC' },
	Jest: { icon: siJest, color: '#C21325' },
	Cypress: { icon: siCypress, color: '#69D3A7' },
	Kover: { icon: siKotlin, color: '#7F52FF' },
	Gatling: { icon: siGatling, color: '#FF6720' },

	Docker: { icon: siDocker, color: '#2496ED' },
	Kubernetes: { icon: siKubernetes, color: '#326CE5' },
	Helm: { icon: siHelm, color: '#0F1689' },
	Istio: { icon: siIstio, color: '#466BB0' },
	Terraform: { icon: siTerraform, color: '#844FBA' },
	Ansible: { icon: siAnsible, color: '#EE0000' },
	Linux: { icon: siLinux, color: '#FCC624' },
	'GitLab CI': { icon: siGitlab, color: '#FC6D26' },
	'GitHub Actions': { icon: siGithubactions, color: '#2088FF' },

	PostgreSQL: { icon: siPostgresql, color: '#4169E1' },
	Oracle: { icon: null, color: '#F80000' },
	YDB: { icon: null, color: '#FF0000' },
	MongoDB: { icon: siMongodb, color: '#47A248' },
	ClickHouse: { icon: siClickhouse, color: '#FFCC01' },
	Neo4j: { icon: siNeo4j, color: '#4581C3' },

	Kafka: { icon: siApachekafka, color: '#231F20' },
	RabbitMQ: { icon: siRabbitmq, color: '#FF6600' },
	Celery: { icon: siCelery, color: '#37814A' },
	Redis: { icon: siRedis, color: '#FF4438' },
	MinIO: { icon: siMinio, color: '#C72E49' },
	Nginx: { icon: siNginx, color: '#009639' },
	Traefik: { icon: siTraefikproxy, color: '#24A1C1' },
	Elasticsearch: { icon: siElasticsearch, color: '#005571' },
	Keycloak: { icon: siKeycloak, color: '#4D4D4D' },
	Vault: { icon: siVault, color: '#FFEC6E' },
	pgAdmin: { icon: siPostgresql, color: '#336791' },

	'ELK Stack': { icon: siElasticstack, color: '#005571' },
	Prometheus: { icon: siPrometheus, color: '#E6522C' },
	Grafana: { icon: siGrafana, color: '#F46800' },
	Loki: { icon: siGrafana, color: '#F5A623' },
	Alloy: { icon: siGrafana, color: '#F46800' },
	Tempo: { icon: siGrafana, color: '#F46800' },

	PyTorch: { icon: siPytorch, color: '#EE4C2C' },
	'scikit-learn': { icon: siScikitlearn, color: '#F7931E' },
	MLX: { icon: siApple, color: '#000000' },
	'Hugging Face': { icon: siHuggingface, color: '#FFD21E' },
	LangChain: { icon: siLangchain, color: '#1C3C3C' },
	Claude: { icon: siAnthropic, color: '#D97757' },
	Ollama: { icon: siOllama, color: '#000000' },
	'LM Studio': { icon: siLmstudio, color: '#A020F0' },

	Git: { icon: siGit, color: '#F05032' },
	Zsh: { icon: siZsh, color: '#F15A24' },
	Maven: { icon: siApachemaven, color: '#C71A36' },
	Gradle: { icon: siGradle, color: '#02303A' },
	Make: { icon: siCmake, color: '#6D00CC' },
	npm: { icon: siNpm, color: '#CB3837' },
	Bun: { icon: siBun, color: '#000000' },
	Postman: { icon: siPostman, color: '#FF6C37' },
	Bruno: { icon: siBruno, color: '#F4A118' },
	Wireshark: { icon: siWireshark, color: '#1679A7' },
	nmap: { icon: null, color: '#4682B4' },
	Obsidian: { icon: siObsidian, color: '#7C3AED' },
	Figma: { icon: siFigma, color: '#F24E1E' },
	Jupyter: { icon: siJupyter, color: '#F37626' },
	n8n: { icon: siN8n, color: '#EA4B71' },
	Jira: { icon: siJira, color: '#0052CC' },

	Neovim: { icon: siNeovim, color: '#57A143' },
	'VS Code': { icon: null, color: '#007ACC' },
	'IntelliJ IDEA': { icon: siIntellijidea, color: '#000000' },
	PyCharm: { icon: siPycharm, color: '#21D789' }
};

export function readableTextColor(bgHex: string): string {
	const hex = bgHex.replace('#', '');
	const r = parseInt(hex.slice(0, 2), 16);
	const g = parseInt(hex.slice(2, 4), 16);
	const b = parseInt(hex.slice(4, 6), 16);
	const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
	return luminance > 0.6 ? '#000000' : '#ffffff';
}
