apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nevenotes-tech.fullname" . }}
  labels:
    {{- include "nevenotes-tech.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nevenotes-tech.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nevenotes-tech.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: ORIGIN
              value: {{ .Values.origin | quote }}
            - name: PORT
              value: {{ .Values.service.targetPort | quote }}
          envFrom:
            - secretRef:
                name: {{ include "nevenotes-tech.secretName" . }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
