{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nevenotes-tech.secretName" . }}
  labels:
    {{- include "nevenotes-tech.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  S3_ENDPOINT: {{ .Values.secret.s3Endpoint | quote }}
  S3_ACCESS_KEY_ID: {{ .Values.secret.s3AccessKeyId | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.secret.s3SecretAccessKey | quote }}
  S3_BUCKET: {{ .Values.secret.s3Bucket | quote }}
{{- end }}
